### ISSUE TITLE
Scrolling?

### ISSUE THREAD

**Issue by mexindian** [ThomasSiegmund/D3TableFilter#10]
It seems the original table allows for an object: `fixed_headers` which allows for scrolling, has this been passed to this package? For very wide tables, I need to be able to scroll the page, but the html page that is born does not have scroll-bars enabled.

**Comment by ThomasSiegmund** [comment]
This function of TableFilter never worked for me, not even the plain demo from the TableFilter web site:

http://tablefilter.free.fr/fixed-headers2.htm

So it also won't work in the D3TableFilter environment.

Sorry

Thomas

**Comment by mexindian** [comment]
True, even those fixed headers weren't fixed... but they allow for scollbars... 
![image](https://cloud.githubusercontent.com/assets/8094091/14252734/2718eecc-fa78-11e5-972d-59a66a234fa5.png)

How could I enable the same functionality in D3TableFilter?

**Comment by ThomasSiegmund** [comment]
Vertical scroll bars should show up whenever needed. Please provide an example where you miss them.

For horizontal scroll bars you may need to specify absolute column widths. In the context of a bootstrap layout, e.g. in a shiny app, there will be no scroll bars because the bootstrap grid system will define the available space. Within this space TableFilter will adjust the column widths accordingly automatically to make the table fit. To avoid this you could specify the column widths in absolute pixels, e.g 

```r
tableProps <- list(
        # fixed column width
        col_width = list("150px", "200px")
    );

```

**Comment by mexindian** [comment]
Hi Thomas. Actually, the opposite seems to be true... the table dynamically re-sizes horizontally to fit the content, so scrollbars are not required. The vertical scrollbar however does not show up:
![image](https://cloud.githubusercontent.com/assets/8094091/14350156/2ff93916-fcb7-11e5-82b1-8f94c749b913.png)

**Comment by mexindian** [comment]
I also had another hypothesis... perhaps the vertical scrollbar doesn't show up if the original table is small enough to fit into one 'screen-ful'... So I made my table very long so that when the table loads it's already too long... and still the scrollbars do not spawn.

I'm using windows 10. In Chrome, the scroll-bar doesn't show up at all. In IE, the scroll-bar shows up, but is full in other words, it thinks there's no content to scroll...
![image](https://cloud.githubusercontent.com/assets/8094091/14350448/e2dbdcea-fcb8-11e5-86c9-27910b4fc4ba.png)

**Comment by ThomasSiegmund** [comment]
I guess a reproducible example and a screenshot might help ...

**Comment by mexindian** [comment]
Sorry, I should have started there. Here you go:
```
B <- data.frame(a=1:200,b=1:200,c=1:200,d=1:200)
  c <- d3tf(B,
     selectableRowsClass = "warning")
```
I expect that to have vertical scrollbars , correct?

**Comment by ThomasSiegmund** [comment]
Ah, I see. Usually I don't use the widget outside of Shiny apps. The vertical scrollbars will show up if you specify the height in the d3tf() call:

```r
d3tf(B, height = "400px")
```
or

```r
d3tf(B, height = "auto")

```

Within Shiny the heigth is specified in d3tfOutput().

**Comment by mexindian** [comment]
Correct. Perfect, thank you.
