### ISSUE TITLE
No way to reset editions

### ISSUE THREAD

**Issue by user05011988** [ThomasSiegmund/D3TableFilter#13]
Hi Thomas,

I find no way to reset editions from previous data when I change the data to use in the table. I would like to put again input$mtcars_edit=NULL every time I load new data to be used in the table of the interface.

I have tried to reset the input through shinyjs or to play with attr, but it doesn't work.

Is there any way to solve this problem? It is necessary to find a solution to be able to publish a shiny application using your package.

Kind regards,

Daniel

**Comment by ThomasSiegmund** [comment]
Hi Daniel,

could you please give the current version a try? I have added a message handler to reset inputs.

```r
      session$sendCustomMessage(type = "resetValue", message = "mtcars_edit")
```

Cheers

Thomas

**Comment by user05011988** [comment]
Hi Thomas,

i'll do it tomorrow when I arrive to work,  and I'll share the results also in StackOverflow if succesful

thanks for the effort provided.

Freundliche Grüße

Daniel



Sent from my Mi phone
On Thomas Siegmund <notifications@github.com>, 12 Oct 2016 20:12 wrote:

Hi Daniel,

could you please give the current version a try? I have added a message handler to reset inputs.

      session$sendCustomMessage(type = "resetValue", message = "mtcars_edit")

Cheers

Thomas

**Comment by user05011988** [comment]
Hi Thomas,

The solution is incompatible with DT package. Tables generated through this package cannot be loaded. Whne I comment the four lines you added the problem is solved.  I'll try to convert the DT table to a D3tablefilter table, but it is better you know it.

Cheers,

Daniel

**Comment by user05011988** [comment]
I have problem with the selection of rows. I wanted to find the solution through analysis of 'interaction' example, but the row selection of the second tab doesn't work. When you fix it, I'll be in theory able to load the necessary table to run the app and check if your solution for resetting input works.

Cheers,

Daniel

**Comment by user05011988** [comment]
I've been able to solve in theory the problem of not being able to reset inputs with a system of checks that disables edition of all columns of table when I load a new dataset into the table.

I see that I can now look to the row selection interaction example, so my intutition is that rowselection was affected by change in code you performed during last commit. Adding to DT problem commented before, I think you really cancel last commit until not being sure about possible unexpected consequences.

I hope these comment have helped you.

**Comment by ThomasSiegmund** [comment]
Hi,

I've modified the previous solution to avoid conflicts with other packages. There is now a "resetInput" function.

```r
      resetInput(session, "mtcars_edit")
```

Please let me know if this works for you.

Best

Thomas

**Comment by user05011988** [comment]
Hi 

Thank you. I was beginning to have issues with my system to deal with this problem, so I´ll try it tomorrow.

LG

Daniel

**Comment by user05011988** [comment]
It is working. I'll let you know if I find issues in the future.

Thnak you very much for the help provided.

Daniel
