### ISSUE TITLE
Accessing row data in Shiny

### ISSUE THREAD

**Issue by JoshMB8** [ThomasSiegmund/D3TableFilter#15]
Firstly loving this package, the filters and edit-ability are much better than other table packages I have come across. 
 
Secondly this is more of a question than an issue. I apologise if the answer is obvious or that I've missed it in the documentation, I'm fairly new to both this package and using shiny.

How would I go about accessing the information of a D3Table in Shiny?

For example if you were to use the DT package in shiny you could get info as follows:
in ui: dataTableOutput("x")
in server: input$x_rows_selected
This would return the row number, which you could use as an input for a function.

Similarly you can do the same with input$x_cell_clicked for the info within a specific cell. 

So my question is is there an equivalent for this package as I am creating an app where once a row is selected the Row number is taken and entered into a function to create another table.

Thank you for the help.

**Comment by ThomasSiegmund** [comment]
Thanks for the comments. 

For the row selection there is input$tableID_select, for edit events input$tableID_edit. Filtering can be observed in input$tableID_filter. See [examples/interaction](https://github.com/ThomasSiegmund/D3TableFilter/blob/master/inst/examples/interaction/server.R) for example code.

 Alternatively you can get the filtered rows using [crosstalk](http://rstudio.github.io/crosstalk/). See [examples/crosstalk](https://github.com/ThomasSiegmund/D3TableFilter/tree/master/inst/examples/crosstalk).

Best

Thomas

**Comment by JoshMB8** [comment]
Great thank you for the quick response.
