### ISSUE TITLE
Is there a way to fill an edit down a column?

### ISSUE THREAD

**Issue by andoni34** [ThomasSiegmund/D3TableFilter#16]
As in, can you fill an edit in one row down the entire table, pasting the edit in ever subsequent row? Thanks.

**Comment by ThomasSiegmund** [comment]
No, there is no such feature in D3TableFilter. If you need spreadsheet-like table editing you could have a look at [rhandsontable](https://cran.r-project.org/web/packages/rhandsontable/).

**Comment by andoni34** [comment]
Thank you, that may work for my purposes.
