### ISSUE TITLE
Pre-select of Rows

### ISSUE THREAD

**Issue by JoshMB8** [ThomasSiegmund/D3TableFilter#17]
Hi Thomas,

Thank you again for your help with my previous question, really helped me out with my project.
I have another question regarding the 'pre-selection' of rows in a table. 
I have managed to implement what I believe to be the correct method as rows are pre-selected when the table is generated. However I don't know how to/ seem to be able to work out how to make sure the first row of the table is selected.

Below is the code I have to render my table, using the rowStyles as suggested by documentaion for pre-selection of rows. 

`d3tf(y, tableProps = tableProps, edit = FALSE, selectableRows = 'single', extensions = extensions, rowStyles = c(rep("", 1), rep("info", 1)));`

However this seems to pre-select the second row. 
as shown: 
![d3tf row select](https://cloud.githubusercontent.com/assets/26301639/25012450/7921f7d8-2068-11e7-81a0-99c39f3a0aa2.jpg)

I'm sure this is another easy fix but again I haven't been able to find/ work out a solution based on the documentation. Any help with this would be greatly appreciated.

Thank you again for your help and for this great package!

**Comment by ThomasSiegmund** [comment]
rowStyles ist a character vector of the same length as the number oft  rows. To select the first row only:

 rowStyles=c("info", rep("", nrow(y)-1))

**Comment by JoshMB8** [comment]
Perfect thank you very much!
