### ISSUE TITLE
Column Editing

### ISSUE THREAD

**Issue by afpapa2** [ThomasSiegmund/D3TableFilter#23]
Not necessarily an issue as much as a suggestion/annoyance.

When editing a column and pausing briefly, the edit is confirmed (brief green flash) and the cursor is reset to the entry-point of the cell. It makes more sense to leave the cursor at its current position so that the user can continue to edit at that location.

If you pause mid-sentence during an edit you have to re-click your last cursor location to continue editing in the same spot.

**Comment by ThomasSiegmund** [comment]
Minor bug in the examples app: If you leave out the ```r value``` argument in the ```r confirmEdit``` call, only the color changes, not the cursor position.

https://github.com/ThomasSiegmund/D3TableFilter/blob/828be5fb2fbc608f26cbb96c3ede3a5248c38d6b/inst/examples/interaction/server.R#L101

![edit](https://user-images.githubusercontent.com/7164268/33519365-a9d56d98-d7a5-11e7-9e7b-fa8c4a877795.gif)
