### ISSUE TITLE
R 3.4.3 Compatibility?

### ISSUE THREAD

**Issue by songjh9618** [ThomasSiegmund/D3TableFilter#27]
It seems that the package is currently not compatible with R 3.4.3?

```R
> install.packages("D3TableFilter")
Warning message:
package ‘D3TableFilter’ is not available (for R version 3.4.3)
```

**Comment by ThomasSiegmund** [comment]
D3Tablefilter is not available in CRAN. Please install with

install.packages("devtools")
devtools::install_github("ThomasSiegmund/D3TableFilter")
