### ISSUE TITLE
Turning off filtering option

### ISSUE THREAD

**Issue by RajarshiBhadra** [ThomasSiegmund/D3TableFilter#5]
Is there any way I can turn off the filtering option?

**Comment by ThomasSiegmund** [comment]
You can 

- disable TableFilter completely using the enableTf option of d3tf 
```
d3tf(mtcars, enableTf = FALSE)
```

- disable the filter grid using the grid  option of TableFilter
```r
tableProps <- list(grid = FALSE) 
d3tf(mtcars,
         enableTf = TRUE,
         tableProps = tableProps
)
```
- disable the filter for single columns in tableProps, e.g.:
```r
tableProps <- list( col_2: "none") 
d3tf(mtcars,
         enableTf = TRUE,
         tableProps = tableProps
)
```
