### ISSUE TITLE
custom_slc_options

### ISSUE THREAD

**Issue by dlennon** [ThomasSiegmund/D3TableFilter#6]
Is this customization from HTML table filter available for D3TableFilter?

**Comment by ThomasSiegmund** [comment]
All configuration options from html table filter should be available. Basically you only have to express the JavaScript objects as nested lists in R. D3TableFilter translates this into JSON objects using jsonlite and passes the configuration object to the table filter generator javascript. 

The custom_slc_options example from the tablefiler doc (http://tablefilter.free.fr/doc.php) should read like this:

```r
tableProps <- list(
  col_3 = "multiple",
  col_5 = "multiple",
  custom_slc_options = list(
    cols = list(3, 5),
    texts = list('', list('1500 - 2000','2000 - 5000','5000 - 15000','15000 - 25000')), 
    values = list(list('Perl','C++','Suite'), list('>=1500 && <=2000','>2000 && <=5000','>5000 &&  <=15000','>15000 && <=25000')),
    sorts = list(FALSE, FALSE)
  )
)
d3tf(df, tableProps = tableProps, ...)

```

**Comment by ThomasSiegmund** [comment]
Works.
