### ISSUE TITLE
Fixed Header for the D3 table

### ISSUE THREAD

**Issue by Atan1988** [ThomasSiegmund/D3TableFilter#8]
Hi Thomas,

     I would like to first thank you for this amazing package. It is the only table I can find that allows edits. The advanced filters are also very handy.  However, is there a way to fix the header for the table or separate the table into multiple pages like the DT::datatables?

Thanks!
Allen

**Comment by ThomasSiegmund** [comment]
Hi Allen,

thanks for the nice comments.

> It is the only table I can find that allows edits.

rhandsontable for example also has nice editing capabilities.

> However, is there a way to fix the header for the table or separate the table into multiple pages

You can set paging = TRUE in tableProps. This gives something like

http://tablefilter.free.fr/datademo2.htm
 
Please have a look at the TableFilter documentation, there are lots of options for paging.

http://tablefilter.free.fr/doc.php#paging

Best

Thomas

**Comment by Atan1988** [comment]
Thanks, Thomas!  The documentation should allow me to explore more of the features.  I will look into the rhandsontable package as well.
